openapi: 3.0.1
info:
  description: 画像変換
  title: Image Converter
  version: 1.0.0
servers:
- url: http://127.0.0.1:5000/
- url: http://localhost:5000/
tags:
- name: url
paths:
  /url:
    get:
      description: urlを入力に、画像を出力する
      operationId: get_image_for_url
      parameters:
      - explode: true
        in: query
        name: url
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: successful operation
      summary: urlを入力に、画像を出力する
      tags:
      - url
      x-openapi-router-controller: openapi_server.controllers.url_controller
components:
  schemas: {}
